Rework of DOM shim (using parse5) to allow for element properties in the future
ProjectEvergreen/wcc pull request #178
Opened 2024-11-21 21:54 UTC by briangrider

## Related Issue
[First step to resolving issue 170](https://github.com/ProjectEvergreen/wcc/issues/170)

## Summary of Changes

dom-shim.js:
1. [x] Reworked DOM shim to use parse5 for serializing children and parsing strings for innerHTML getter and setter
2. [x] Added isShadowRoot utility function to check prototype when assessing whether shadowrootmode attribute needs to be added to appended templates
3. [x] Added deepClone utility function to be used with cloneDeep(deep) functionality
4. [x] Added getParse5ElementDefaults utility function to generate empty parse5 elements with much less overhead. At least 2-5x performance gain compared to parsing an empty element in a string (ie. '<template></template>')
5. [x] Added various "TODO" comments for considerations for improvement

wcc.js
1. [x] Removed VOID_ELEMENTS (no longer needed)
2. [x] Added markHydrate function to set hydration in definitions
3. [x] Simplified renderComponentRoots significantly - no need for getInnerHTML, innerHTML, elementHTML, elementTree, hasLight anymore
4. [x]  Removed renderLightDomChildren (passes all tests without)
5. [x]  renderToString significantly simplified as well, similar to renderComponentRoots
6. [x]  Various other small improvements/optimizations

2024-11-22 21:19 UTC, thescientist13 reviewed
Will try and give this a more thorough testing soon, but just a couple quick observations:
- Since there are no dependency changes, _package-lock.json_ should probably not be changing
- It looks like the tests failed only because of coverage thresholds, and so I'm fine bumping that as needed (in this case looks like it would be 85%)

2024-11-22 23:41 UTC, briangrider commented
> Will try and give this a more thorough testing soon, but just a couple quick observations:
> 
> * Since there are no dependency changes, _package-lock.json_ should probably not be changing
Ah, my bad. I must have had it accidentally checked on Sourcetree, just reset the branch and pushed just the relevant files

> * It looks like the tests failed only because of coverage thresholds, and so I'm fine bumping down that as needed (in this case to 85% would be ok)
Yes, I believe on my initial commit I was at around 91+% on function coverage but it looks like it dipped to 89.28% with some of the additional changes. Yes, if we can temporarily drop the threshold to 85% that would be great

2024-12-05 14:15 UTC, thescientist13 reviewed
OK, coming out of our chats in #177, here's the state of things

1. [ ] We will land #171 first
1. [ ] preserve `getHTML` in the DOM shim and make sure no other APIs are being removed (and we should probably add some test cases here, which I can help with)
1. [ ] I am OK to let the mode fix come in as part of this PR, but let's make sure by adding a test case - https://github.com/ProjectEvergreen/wcc/issues/65
1. [ ] Looks like this PR would also help resolve or invalidate https://github.com/ProjectEvergreen/wcc/issues/16 ?
1. [ ] Sanity test in Greenwood (I will help with this once this gets rebased after #171 lands)

2025-01-17 17:54 UTC, briangrider commented
> 3. [ ]  preserve `getHTML` in the DOM shim and make sure no other APIs are being removed (and we should probably add some test cases here, which I can help with)
I think we should be good here but let me know.

> 4. [ ]  I am OK to let the mode fix come in as part of this PR, but let's make sure by adding a test case - [support configurable `shadowrootmode` attribute for `<template>` tags #65](https://github.com/ProjectEvergreen/wcc/issues/65)
This seems to be the last step here on my end. Will have this done soon.

> 5. [ ]  Looks like this PR would also help resolve or invalidate [verify / ensure proper serialization of shadow roots excluding closed shadow roots from `getInnerHTML` #16](https://github.com/ProjectEvergreen/wcc/issues/16) ?
Yes, I believe so.

2025-01-17 19:17 UTC, thescientist13 reviewed
Looking good!

Just left a few comment / questions, but let me go ahead and start doing some downstream testing of this in Greenwood in the meantime.

2025-01-17 19:17 UTC, thescientist13 commented on test/cases/shadowrootmode/shadowrootmode.spec.js
> +    console.log('hello', html);
clean up `console.log`

2025-01-17 19:17 UTC, thescientist13 commented on test/cases/shadowrootmode/shadowrootmode.spec.js
> + * Should return the expected HTML output based on the shadow root mode of each component
Minor suggestion here to maybe get a little more technical / specific on the result here

> _Should return the expected attribute value for shadowrootmode on the template tag based on the shadow root mode of each component_

2025-01-17 19:17 UTC, thescientist13 commented on test/cases/create-document-fragment/create-document-fragment.spec.js
> + * Run wcc against a custom element which creates a document fragment
Sorry, I might have the lost recollection on this, but was there a particular need to test for document fragment specifically?  Not sure if the case / result maybe just need to cover a little bit more of the why, maybe that would help jog my recollection?

2025-01-17 19:17 UTC, thescientist13 commented on src/dom-shim.js
> +    // TODO Should we throw an error here when a tagName is already defined?
do we need this comment?  Seems its similar as the comment below?

2025-01-17 19:17 UTC, thescientist13 commented on src/dom-shim.js
> +// TODO Should go into utils file?
re: utils file, if its not needed in other files, it's probably fine to leave.  I think there are cases for a util file between wcc and jsx-loader I think, but I think for now we can probably just move the `TODO` comment, but certainly open to a PR that proposes some code structuring / organization.

2025-01-17 19:17 UTC, thescientist13 commented on src/dom-shim.js
> +// structuredClone doesn't work with functions. TODO This works with
Are you suggesting a library would / could handle functions?  If we think that feature would be helpful, I would prefer we just extend this to support our needs if so.  (would prefer to keep dependencies in this project as slim as possible and already watch to try and better de-couple the JSX ones).

So yeah, if we want to keep iterating on this, I am happy to have an issue / PR to do, and we can clean up the TODO comment.

2025-01-17 19:17 UTC, thescientist13 commented on src/dom-shim.js
> +// TODO Should this go into a utils files?
same: re utils file comment

2025-01-17 20:11 UTC, thescientist13 requested changes
So did some downstream testing in Greenwood and I see one regression related to how WCC is handling `<html>`, `<head>` and `<body>` tags it seems, in that it looks like they are being stripped out by WCC now.

For example, this "app layout" component
https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/test/cases/build.default.workspace-layouts-page-and-app-dynamic/src/layouts/app.js
```js
export default class AppLayout extends HTMLElement {
  async connectedCallback() {
    const year = new Date().getFullYear();

    this.innerHTML = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>App Layout</title>
        </head>

        <body>
          <h1>App Layout</h1>
          <page-outlet></page-outlet>
          <footer>${year}</footer>
        </body>
      </html>
    `;
  }
}
```

when run through WCC, doesn't seem to be returning all the content (notice the `<title>` tag is not wrapped by a `<head>` tag anymore)
```sh
{
  result: {
    layout: null,
    body: '\n' +
      '      \n' +
      '      \n' +
      '        \n' +
      '          <title>App Layout</title>\n' +
      '        \n' +
      '\n' +
      '        \n' +
      '          <h1>App Layout</h1>\n' +
      '          <page-outlet></page-outlet>\n' +
      '          <footer>2025</footer>\n' +
      '        \n' +
      '      \n' +
      '    ',
    frontmatter: null,
    html: null,
    prerender: false,
    isolation: undefined
  }
}
```

----

My hunch is that in DOM shim, now that we are pulling in parse5, we are only using `parseFragment`
https://github.com/ProjectEvergreen/wcc/pull/178/files#diff-d043dc2785231f2ef65d347d7810dae3ca0224e06f777e6d3d66ccc18c5132eeR3

but like in _wcc.js_ we should probably be detecting and using `parse` _or_ `parseFragment`
https://github.com/ProjectEvergreen/wcc/blob/master/src/wcc.js#L31

This may be an oversight in the WCC test case, so let's add a new one specifically testing for full document support and I bet it will fail, then we can add the parsing detection, then I bet it will work.  🎯

2025-01-19 23:09 UTC, thescientist13 commented on test/cases/light-dom/src/pages/index.js
> +    return `<!DOCTYPE html>
since we have dedicated test cases for the wrapping tags, maybe we can leave this test case as is?

2025-01-19 23:32 UTC, thescientist13 reviewed
Awesome, just sanity checked the latest changes against Greenwood's test suite (and website repo) and everything looks to be working great!
https://github.com/ProjectEvergreen/greenwood/pull/1340/commits/1be1553711a8c48bb36b222312d05543a163df71

Only last thing I commented on was re: [this test case](https://github.com/ProjectEvergreen/wcc/pull/178/files#r1921653872), otherwise I think this is looking good to go.  💯

2025-01-20 00:49 UTC, thescientist13 approved these changes
Heck yeah, awesome work @briangrider ! 🙇

2025-01-20 00:50 UTC, merged

2025-01-20 15:09 UTC, briangrider commented
> Heck yeah, awesome work @briangrider ! 🙇

Happy to help!